language: python
python:
- '2.7'
- '3.3'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success:
- codecov
before_install:
- openssl aes-256-cbc -K $encrypted_3e0bff1a2c53_key -iv $encrypted_3e0bff1a2c53_iv
  -in deploy_rsa.enc -out deploy_rsa -d

addons:
  # add our deploy server to known hosts
  # you can set environmental variable in Travis GUI:
  ssh_known_hosts: moon.scs.ryerson.ca 

before_deploy:
- openssl aes-256-cbc -K $encrypted_3e0bff1a2c53_key -iv $encrypted_3e0bff1a2c53_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

# deploy using rsync or scp
# setup ENV ($) variables in the web interface
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet 
     ${TRAVIS_BUILD_DIR}/ci_play      
     ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/${DEPLOY_USER}
  on:
    branch: master
